LINUX API: ETH_SWITCH
ETH_SWITCH
Functions
int switch_init ()
int switch_set_config (SW_PORT port_num, port_config config)
bool switch_get_config (SW_PORT port_num, port_config *config)
bool switch_port_reset (SW_PORT port_num)
Detailed Description
Additional documentation for group 'ETH_SWITCH'
Function Documentation
switch_get_config()
bool switch_get_config (SW_PORT port_num, port_config * config)
Get config of switch port
Parameters
[in] port number fromSW_PORT enum
[out] structure pointer containing configuration data
Returns
status of function(True/False)
References port_config::port_dns, port_config::port_gateway, port_config::port_ip, port_config::port_mode, and port_config::port_prefix.
switch_init()
int switch_init ()
Initialize ethernet switch
Returns
error code from ERROR_CODE enum
References switch_port_reset().
switch_port_reset()
bool switch_port_reset (SW_PORT port_num)
Reset switch port
Parameters
[in] port number from SW_PORT enum
Returns
status of function(True/False)
Referenced by switch_init(), and switch_set_config().
switch_set_config()
int switch_set_config (SW_PORT port_num, port_config config)
Set config for switch port
Parameters
[in] port number from SW_PORT enum
[in] structure containing configuration data
Returns
error code from ERROR_CODE enum
References port_config::port_dns, port_config::port_gateway, port_config::port_ip, port_config::port_mode, port_config::port_prefix, and switch_port_reset().