LINUX API: SIM
SIM
Functions
bool sim_unlock (int pincode)
bool sim_deactivate ()
bool sim_dialup_connect (unsigned char phone_no[])
bool sim_dialup_disconnect ()
bool sim_set_ap (sim_apn setapn)
bool sim_list_ap (vector *aplist)
bool sim_remove_ap (char *ap_name)
bool sim_connect_to_internet ()
char * sim_get_ipaddress ()
int sim_get_signal_strength ()
char * sim_get_imsi ()
char * sim_get_imei ()
bool sim_send_sms (char *phoneno, char *message)
Detailed Description
Additional documention for group 'SIM'
Function Documentation
sim_connect_to_internet()
bool sim_connect_to_internet ()
Connect to internet
Returns
status of function (ture or false)
References sim_get_ipaddress().
sim_deactivate()
bool sim_deactivate ()
Deactivate sim by powering the module off
Returns
status of function (ture or false)
References write_value_to_output_gpio().
sim_dialup_connect()
bool sim_dialup_connect (unsigned char phone_no[])
Connect to telephone network to dial
Parameters
[in] Phone_no unsigned char type variable
Returns
status of function (ture or false)
sim_dialup_disconnect()
bool sim_dialup_disconnect ()
Disconnect from telephone network
Returns
status of function (ture or false)
sim_get_imei()
char* sim_get_imei ()
Get the IMEI
Returns
IMEI number
sim_get_imsi()
char* sim_get_imsi ()
Get the IMSI
Returns
IMSI number
sim_get_ipaddress()
char* sim_get_ipaddress ()
Get ip address
Returns
ip address
Referenced by sim_connect_to_internet().
sim_get_signal_strength()
int sim_get_signal_strength ()
Get the strengh of the signal (in dbm)
Returns
signal strength in dbm
sim_list_ap()
bool sim_list_ap (vector * aplist)
list already configured AP
Parameters
[out] vector typedef structure for list of sim_apn.
Returns
status of function (ture or false)
References sim_apn::apn_name, sim_apn::apnProtocol, sim_apn::authentication, sim_apn::password, and sim_apn::username.
sim_remove_ap()
bool sim_remove_ap (char * ap_name)
Remove an AP from the list (identified by its name)
Parameters
ap_name charater type variable
Returns
status of function (ture or false)
sim_send_sms()
bool sim_send_sms (char * phoneno, char * message)
Send the SMS
Parameters
[in] message character type variable.
[in] phone_no character type variable.
Returns
status of function (ture or false)
sim_set_ap()
bool sim_set_ap (sim_apn setapn)
Create or update an AP (identified by its name) < Max 16 APs can be configured at a time >
Parameters
[in] apn struct type argument
Returns
status of function (ture or false)
References sim_apn::apn_name, sim_apn::apnProtocol, sim_apn::authentication, sim_apn::password, and sim_apn::username.
sim_unlock()
bool sim_unlock (int pincode)
Activate the sim card by using sim pin
Parameters
[in] pincode integer type variable
Returns
status of function (ture or false)