LINUX API: GPS
GPS
Functions
int open_port ()
char * state_gps (int filedescriptor)
char * read_data_gprmc (int filedescriptor)
char * read_data_gprmc_parse (int filedescriptor, int index)
char * read_data_gpgga (int filedescriptor)
char * read_data_gpgga_parse (int filedescriptor, int index)
bool close_port (int filedescriptor)
Detailed Description
Additional documentation for group 'GPS'
Function Documentation
close_port()
bool close_port (int filedescriptor)
Close GPS serial link
Parameters
[in] filedescriptor FD of opened port
Returns
status of function
open_port()
int open_port ()
Open GPS serial link
Returns
File Descriptor of open port
read_data_gpgga()
char* read_data_gpgga (int filedescriptor)
Output full GPGGA of 1 frame
Parameters
[in] filedescriptor FD of opened port
Returns
frame of GPGGA data
Referenced by read_data_gpgga_parse().
read_data_gpgga_parse()
char* read_data_gpgga_parse (int filedescriptor, int index)
Extract part of GPGGA of 1 frame
Parameters
[in] filedescriptor FD of opened port
[in] index
Returns
required GPGGA data
References read_data_gpgga().
read_data_gprmc()
char* read_data_gprmc (int filedescriptor)
Output full GPRMC of 1 frame
Parameters
[in] filedescriptor FD of opened port
Returns
frame of GPRMC data
Referenced by read_data_gprmc_parse().
read_data_gprmc_parse()
char* read_data_gprmc_parse (int filedescriptor, int index)
Extract part of GPRMC of 1 frame
Parameters
[in] filedescriptor FD of opened port
[in] index
Returns
required gprmc data
References read_data_gprmc().
state_gps()
char* state_gps (int filedescriptor)
State of GPS
Parameters
[in] filedescriptor FD of opened port
Returns
frame of PSTMANTENNASTATUS data