LINUX API: WIFI
WIFI
Functions
bool wifi_activation (bool state)
bool wifi_get_power_status ()
bool wifi_set_defaultpower_mode (bool powermode)
bool wifi_get_defaultpower_mode ()
int wifi_connect_network (wifi_info credentials)
bool wifi_disconnect_network ()
bool wifi_add_to_ssid_preferred_list (wifi_info credentials)
bool wifi_get_ssid_preferred_list (vector *con_list)
int wifi_remove_from_ssid_preferred_list (char *ssid)
bool wifi_clean_ssid_preferred_list ()
int wifi_get_signal_strength (char *ssid)
bool wifi_scan (vector *v)
bool wifi_reconnect ()
bool wifi_set_ssid_lock (char *ssid, bool enable)
bool wifi_set_static (char *ipaddress, char *prefixnetmask, char *gateway, char *dns)
bool wifi_use_dhcp (bool enable)
bool wifi_mode (bool mode, wifi_info apn)
Detailed Description
Additional documentation for group 'WIFI'
Function Documentation
wifi_activation()
bool wifi_activation (bool state)
Turn on WiFi.
Parameters
[in] state true or false to change the state of wifi
Returns
status of function.
wifi_add_to_ssid_preferred_list()
bool wifi_add_to_ssid_preferred_list (wifi_info credentials)
Add the SSID to preferred list
Parameters
[in] wifi_info structure type variable
See also
wifi_info
Returns
status of function.
References wifi_info::password, wifi_info::ssid, and wifi_get_power_status().
wifi_clean_ssid_preferred_list()
bool wifi_clean_ssid_preferred_list ()
Clean the SSID preferred list
Returns
status of function.
References wifi_info::password, wifi_info::ssid, wifi_get_power_status(), wifi_get_ssid_preferred_list(), and wifi_remove_from_ssid_preferred_list().
wifi_connect_network()
int wifi_connect_network (wifi_info credentials)
Connect to a WiFi network
Parameters
[in] wifi_info structure type variable
See also
wifi_info
Returns
Success/Error codes will be returened
See also
enum WIFI_CODES
References wifi_info::password, wifi_info::ssid, and wifi_get_power_status().
wifi_disconnect_network()
bool wifi_disconnect_network ()
Disconnect from currently activate WiFi network
Returns
status of function.
References wifi_get_power_status().
wifi_get_defaultpower_mode()
bool wifi_get_defaultpower_mode ()
Get WiFi power mode when the system starts.
Returns
status of default power mode
wifi_get_power_status()
bool wifi_get_power_status ()
Check whether WiFi is turned on or off.
Returns
status of power.
Referenced by wifi_add_to_ssid_preferred_list(), wifi_clean_ssid_preferred_list(), wifi_connect_network(), wifi_disconnect_network(), wifi_get_signal_strength(), wifi_get_ssid_preferred_list(), wifi_mode(), wifi_reconnect(), wifi_remove_from_ssid_preferred_list(), wifi_scan(), wifi_set_ssid_lock(), wifi_set_static(), and wifi_use_dhcp().
wifi_get_signal_strength()
int wifi_get_signal_strength (char * ssid)
Get WiFi signal strength
Parameters
[in] SSID charcter type variable
[in] strength integer type variable
Returns
strenght of signal
References wifi_get_power_status().
wifi_get_ssid_preferred_list()
bool wifi_get_ssid_preferred_list (vector * con_list)
Get SSID preferred list
Warning
This function allocates memories for the structure, memory needs to be freed on application side
Parameters
[out] vector typedef structure for list of wifi_info.
Returns
status of function.
References wifi_info::password, wifi_info::ssid, and wifi_get_power_status().
Referenced by wifi_clean_ssid_preferred_list(), and wifi_set_ssid_lock().
wifi_mode()
bool wifi_mode (bool mode, wifi_info apn)
Switch the wifi mode into client or access point.
Parameters
[in] mode bool type variable
[in] wifi_info struct containing AP name and password.
See also
wifi_info
Returns
status of function.
References apn::password, and wifi_get_power_status().
wifi_reconnect()
bool wifi_reconnect ()
Reconnect to the currently connected network if it was disconnected.
Returns
status of function.
References wifi_get_power_status().
wifi_remove_from_ssid_preferred_list()
int wifi_remove_from_ssid_preferred_list (char * ssid)
Remove an item from preferred list
Parameters
[in] SSID character type variable
Returns
status of function.
References wifi_get_power_status().
Referenced by wifi_clean_ssid_preferred_list().
wifi_scan()
bool wifi_scan (vector * v)
Get wifi scan results
Warning
This function allocates memories for the structure, memory needs to be freed on application side
Parameters
[out] vector typedef structure for list of wifi_scanresults.
Returns
status of function.
References wifi_scanresult::channel, wifi_scanresult::security, wifi_scanresult::ssid, wifi_scanresult::strength, and wifi_get_power_status().
wifi_set_defaultpower_mode()
bool wifi_set_defaultpower_mode (bool powermode)
Set WiFi power mode when the system start.
Parameters
[in] powermode
Returns
status of function.
wifi_set_ssid_lock()
bool wifi_set_ssid_lock (char * ssid, bool enable)
Lock to current SSID
Parameters
[in] SSID variable character type variable
[in] enable variable bool type variable
Returns
status of function.
References wifi_info::password, wifi_info::ssid, wifi_get_power_status(), and wifi_get_ssid_preferred_list().
wifi_set_static()
bool wifi_set_static (char * ipaddress, char * prefixnetmask, char * gateway, char * dns)
Set static WiFi IP address
Parameters
[in] ipaddress character type variable
[in] prefixnetmask character type variable (value between 1-32)
[in] getway character type variable
[in] dns character type variable
Returns
status of function.
References wifi_get_power_status().
wifi_use_dhcp()
bool wifi_use_dhcp (bool enable)
Use DHCP to enable or disable dhcp for ip address
Parameters
[in] enable bool type variable
Returns
status of function.
References wifi_get_power_status().