LINUX API: BLUETOOTH
BLUETOOTH
Functions
bool bluetooth_on ()
bool bluetooth_off ()
bool bluetooth_pair_device (unsigned char *devicename)
bool bluetooth_unpair_device (unsigned char *devicename)
bool bluetooth_set_config (bt_config conf)
bt_config bluetooth_get_config ()
bool bluetooth_connect_to_device (char *name)
vector bluetooth_scan ()
Detailed Description
Additional documentation for group 'BLUETOOTH'
Function Documentation
bluetooth_connect_to_device()
bool bluetooth_connect_to_device (char * name)
Connect to bluetooth device
Parameters
[in] name Hardware address of the bluetooth device
Returns
status of function(True/False)
bluetooth_get_config()
bt_config bluetooth_get_config ()
Get bluetooth configuration
Returns
bt_config structure containing configuration data
References bt_config::discoverable, bt_config::discoverabletimeout, bt_config::enabled, bt_config::maxpaired, bt_config::name, and bt_config::radioOn.
bluetooth_off()
bool bluetooth_off ()
Disable bluetooth
Returns
status of function(True/False)
Referenced by bluetooth_set_config().
bluetooth_on()
bool bluetooth_on ()
Activate bluetooth
Returns
status of function(True/False)
References bluetooth_set_config(), bt_config::maxpaired, and bt_config::name.
bluetooth_pair_device()
bool bluetooth_pair_device (unsigned char * devicename)
Pair the device with another device
Parameters
[in] devicename Hardware address of the bluetooth device
Returns
status of function(True/False)
References bt_config::maxpaired.
bluetooth_scan()
vector bluetooth_scan ()
Scan for bluetooth devices
Returns
vector list of bt_scanresult structure containing bluetooth device info
References bt_scanresult::devaddress, and bt_scanresult::devname.
bluetooth_set_config()
bool bluetooth_set_config (bt_config conf)
Configure bluetooth
Parameters
[in] conf bt_config structure having configuration data
Returns
status of function(True/False)
References bluetooth_off(), bt_config::discoverable, bt_config::discoverabletimeout, bt_config::enabled, bt_config::maxpaired, bt_config::name, and bt_config::radioOn.
Referenced by bluetooth_on().
bluetooth_unpair_device()
bool bluetooth_unpair_device (unsigned char * devicename)
Unpair from bluetooth device
Parameters
[in] devicename Hardware address of the bluetooth device
Returns
status of function(True/False)